version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - APP_SERVER_IP=${APP_SERVER_IP:-localhost}
      - APP_SERVER_PORT=${APP_SERVER_PORT:-8000}
      - APP_DATABASE_HOST=${APP_DATABASE_HOST:-localhost}
      - APP_DATABASE_PORT=${APP_DATABASE_PORT:-5432}
      - APP_DATABASE_USER=${APP_DATABASE_USER:-admin}
      - APP_DATABASE_PASSWORD=${APP_DATABASE_PASSWORD:-root}
      - APP_DATABASE_DBNAME=${APP_DATABASE_DBNAME:-memoryCards}
      - APP_DATABASE_SSLMODE=${APP_DATABASE_SSLMODE:-disable}
      - APP_DATABASE_TIMEZONE=${APP_DATABASE_TIMEZONE:-Europe/Moscow}
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: pasteboards
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
