services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_SERVER_IP=${APP_SERVER_IP:-0.0.0.0}
      - APP_SERVER_PORT=${APP_SERVER_PORT:-8000}
      - APP_DATABASE_HOST=${APP_DATABASE_HOST:-db}
      - APP_DATABASE_PORT=${APP_DATABASE_PORT:-5432}
      - APP_DATABASE_USER=${APP_DATABASE_USER:-admin}
      - APP_DATABASE_PASSWORD=${APP_DATABASE_PASSWORD:-root}
      - APP_DATABASE_DBNAME=${APP_DATABASE_DBNAME:-memorycards}
      - APP_DATABASE_SSLMODE=${APP_DATABASE_SSLMODE:-disable}
      - APP_DATABASE_TIMEZONE=${APP_DATABASE_TIMEZONE:-Europe/Moscow}
      - APP_JWT_SIGNINGKEY=${APP_JWT_SIGNINGKEY:-6d936a4ee5d36b6b69457dee30e5002d39c824cc2afccb1775e931fc0f414a28}

    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-memorycards}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
